# Site settings

title: cyber
subtitle: training
email: itrequests@sesync.org
description: Hands-on training courses administered by SESYNC.
copyright: "&copy; National Socio-Environmental Synthesis Center (SESYNC)<br>1 Park Place, Suite 300, Annapolis, MD 21401"

# Build settings

markdown: kramdown
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
baseurl: '/syllabi'
