# Site

title: cyber
subtitle: training
email: itrequests@sesync.org
description: Hands-on training courses administered by SESYNC.
gh-pages: "https://sesync-ci.github.io"
copyright: "&copy; National Socio-Environmental Synthesis Center (SESYNC)<br>1 Park Place, Suite 300, Annapolis, MD 21401"

# Jekyll

future: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
#gems:
#  - jekyll-redirect-from
