---
title:  "SESYNC <br> Cyber Summer Institute <br> Mini-projects"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Welcome

Your team is here to practice.

Your instructors are here to coach. 

---

## Mini-project Goals

**In the time scheduled for Coaching, each team should aim to achieve the following:**

- Collaborate on a GitHub repository.
- Introduce your team via a README (Tuesday).
- Script a reproducible "data-to-document" pipeline.
- Present mini-results (Friday).

---

## Practice #1: Tuesday

1. Choose a git captain, and
    1. (Captain) create a GitHub repo,
    1. (Captain) invite collaborators, and
    1. (Team) accept invitation.
1. (Captain) Create a RStudio project from the repo.
1. (Captain) Start a `README.md` & push files.
1. (Team) Create a RStudio project from the repo.
1. Add to the `REAMDE.md` and merge/push.

---

## Practice #2: Wednesday

1. Discuss your data:
   1. Are your data in tidy tables?
   1. Can you define relationships between tables?
   1. How will you share it within the team?
1. Read data into R and prepare it for a simple analyis or visualization.
1. Update the `README.md` on GitHub.

---

## Practice #3: Thursday

1. Begin to code a simple regression analysis or visualization.
1. Decide on the format of your presentation (consider RMarkdown).
1. Practice your collaborative workflow: stage, commit, pull, and push!

---

## Practice #4: Friday

1. Discuss the first steps of your reproducible pipeline. Can you aquire data programatically?
1. Discuss the final steps of your reproducible pipeline. Should you create a data package?
1. Try to get that regression model working or finish that data visualization.
1. Prepare to present on your mini-project!



